#
# ------------------------------------------------

package:
  name: fastfunc
  version: 0.1.7

source:
    git_url: https://github.com/nschloe/fastfunc.git
    git_rev: master

build:
  number: 0
 

requirements:
  build:
    - python
    - cmake
    - setuptools
    - numpy
    - pipdate
    - pybind11
    
  run:
    - python
    - numpy
    - pipdate
    - pybind11

test:
  imports:
    - fastfunc
    
about:
  home: https://github.com/nschloe/fastfunc
  license: MIT License
  summary: Fast numpy ufunc operations
