package:
  name: dcmstack
  version: master

source:

  git_url: https://github.com/kayarre/dcmstack.git
  #git_tag: v0.6.2

requirements:
  build:
    - python
    - pydicom
    - nibabel

  run:
    - python
    - pydicom
    - nibabel

test:
  requires:
    - nose
  imports:
    - dcmstack
    - dcmstack.dcmstack
    - dcmstack.dcmmeta
    - dcmstack.extract
  commands:
    #- nosetests -P --all-modules -v -w $SRC_DIR/test

about:
  home: https://github.com/moloney/dcmstack
  license: MIT License
  summary: 'The dcmstack software allows series of DICOM images to be stacked into multi-dimensional arrays.'
