package:
  name: simplejson
  version: "3.8.0"

source:
  git_url: https://github.com/simplejson/simplejson.git
  git_rev: v3.8.0


requirements:
  build:
    - python
  run:
    - python

test:
  imports:
    - simplejson
    - simplejson._speedups

about:
  home: http://github.com/simplejson/simplejson
  license: MIT
  summary: Simple, fast, extensible JSON encoder/decoder for Python.
