package:
  name: plotly
  version: !!str 1.8.8

source:
  #fn: plotly-1.7.6.tar.gz
  #url: https://pypi.python.org/packages/source/p/plotly/plotly-1.7.6.tar.gz
  #md5: 074544b27dfed171480166a2f195a2bf
  git_url: https://github.com/kayarre/python-api.git
  git_tag: kayarre-patch-1
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - plotly = plotly:main
    #
    # Would create an entry point called plotly that calls plotly.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - requests
    - six
    - pytz
    #- ordereddict
    - simplejson
    - numpy
    - matplotlib
    - ipython
    - pyzmq
    - pandas
    - scipy
    - numpy
    - ipywidgets

  run:
    - python
    - setuptools
    - requests
    - six
    - pytz
    #- ordereddict
    - simplejson
    - numpy
    - matplotlib
    - ipython
    - pyzmq
    - pandas
    - scipy
    - numpy
    - ipywidgets

test:
  requires:
    # Put any additional test requirements here.  For example
    - nose
    
  # Python imports
  imports:
    - plotly
    - plotly.graph_objs
    - plotly.grid_objs
    - plotly.matplotlylib
    - plotly.matplotlylib.mplexporter
    - plotly.matplotlylib.mplexporter.renderers
    - plotly.plotly
    - plotly.plotly.chunked_requests
    - plotly.widgets

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.
    - nosetests -P --all-modules -v -w $SRC_DIR/plotly/tests


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.


    
about:
  home: https://plot.ly/api/python
  license: MIT
  summary: 'Python plotting library for collaborative, interactive, publication-quality graphs.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml