package:
  name: smop
  version: "0.26.2"

source:
  fn: smop-0.26.2.tar.gz
  url: https://pypi.python.org/packages/source/s/smop/smop-0.26.2.tar.gz
  md5: b5b08eb6fc52c70c0388b6e7a70cdaec
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - smop = smop:main
    #
    # Would create an entry point called smop that calls smop.main()

    - smop = smop.main:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy
    - networkx

  run:
    - python
    - numpy
    - scipy
    - networkx

test:
  # Python imports
  imports:
    - smop

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - smop --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/victorlei/smop
  license: MIT
  summary: 'Matlab to Python converter'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
