package:
  name: nibabel
  version: "2.0.1"

source:
  #fn: nibabel-2.0.1.tar.gz
  #url: https://pypi.python.org/packages/source/n/nibabel/nibabel-2.0.1.tar.gz
  #md5: 3be518fde5ec5b09483d4f28c81dc974
  git_url: https://github.com/kayarre/nibabel.git
  git_tag: 2.0.1

requirements:
  build:
    - python
    - numpy

  run:
    - python
    - numpy

test:
  imports:
    - nibabel
    - nibabel.benchmarks
    - nibabel.externals
    - nibabel.externals.tests
    - nibabel.freesurfer
    - nibabel.freesurfer.tests
    - nibabel.gifti
    - nibabel.gifti.tests
    - nibabel.nicom
    - nibabel.nicom.tests
    - nibabel.testing
    - nibabel.tests
    - nisext
    - nisext.tests

about:
  home: https://nipy.github.io/nibabel
  license: MIT License
  summary: 'Access a multitude of neuroimaging data formats'
