package:
  name: control
  version: "0.7.0"

source:
  #fn: pydicom-0.9.9.tar.gz
  #url: https://pypi.python.org/packages/source/p/pydicom/pydicom-0.9.9.tar.gz
  #md5: a66ca6728e69ba565ab9c8a21740eee8
  #git_url: https://github.com/python-control/python-control.git
  git_url: https://github.com/kayarre/python-control.git
  git_rev: master
  
# patches:
   # List any patch files here
   # - fix.patch


build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
   number: 0

requirements:
  build:
    - python
    - nose
    - matplotlib
    - scipy

  run:
    - python
    - numpy
    - scipy
    - matplotlib

test:
  imports:
    - control

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    #- fabric

about:
  home: http://python-control.sourceforge.net
  license:  BSD License
  summary: 'Python control systems library'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
