{% set name = "dmsh" %}
{% set version = "0.1.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  #url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  #sha256: "b52bfabf321c9b5017bd7895a9728412060b00683cd9cfc6a91ad23625dc3489"

  git_url: https://github.com/kayarre/dmsh.git
  #git_rev: master
  git_tag: fix/remove_scripts

build:
  number: 0
  #entry_points:
    #- dmsh-image = dmsh.cli:image
    #- dmsh-poly = dmsh.cli:poly
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - fastfunc
    - numpy
    - pip
    - pypathlib
    - python
    - scipy
  run:
    - fastfunc
    - numpy
    - pypathlib
    - python
    - scipy

test:
  imports:
    - dmsh
    - dmsh.geometry
  commands:
    #- dmsh-image --help
    #- dmsh-poly --help

about:
  home: "https://github.com/nschloe/dmsh"
  license: "MIT"
  license_family: "MIT"
  license_file: ""
  summary: "The worst mesh generator you'll ever use."
  doc_url: ""
  dev_url: ""

extra:
  recipe-maintainers:
    - kayarre
