# This file created by conda-build 2.0.7
# meta.yaml template originally from:
# /Users/sansomk/code/python/condarecipes/meshio, last modified Mon Oct 24 23:38:15 2016
# ------------------------------------------------

package:
    name: meshio
    version: 1.8.14
source:
    git_url: https://github.com/kayarre/meshio.git
build:
    number: '0'
requirements:
    build:
        - python
        - pipdate
        #- h5py
        #- vtk
        - numpy
        - setuptools
    run:
        - python
        - pipdate
        - h5py
        #- vtk # vtk package not updated for vtk > 6 for py3
        - numpy
        - lxml
test:
    imports:
        - meshio
about:
    home: https://github.com/nschloe/meshio
    license: MIT License
    summary: I/O for various mesh formats
