package:
  name: vtk
  version: "7.0.0"

source:
  fn: VTK-7.0.0.tar.gz
  url: http://www.vtk.org/files/release/7.0/VTK-7.0.0.tar.gz
  sha1: 7719fac36b36965eaf5076542166ba49bbe7afbb

build:
  number: 0

requirements:
  build:
    - gcc # [linux and (py27 or py34 or py35)]
    - mesa # [linux and (py27 or py34 or py35)]
    - cmake
    - python
    - hdf5
  run:
    - mesa # [linux and (py27 or py34 or py35)]
    - libgcc # [linux and (py27 or py34 or py35)]
    - python
    - hdf5
    - msvc_runtime  # [win and (py27 or py34 or py35)]

test:
  requires:
    - numpy
    - pillow

  imports:
    - vtk
    - vtk.vtkChartsCore
    - vtk.vtkCommonCore
    - vtk.vtkFiltersCore
    - vtk.vtkFiltersGeneric
    - vtk.vtkGeovisCore
    - vtk.vtkFiltersHybrid
    - vtk.vtkIOCore
    - vtk.vtkImagingCore
    - vtk.vtkInfovisCore
    - vtk.vtkRenderingCore
    - vtk.vtkViewsCore
    - vtk.vtkRenderingVolume
    - vtk.vtkInteractionWidgets

about:
  home: http://www.vtk.org/
  license: BSD
  summary: VTK is an open-source, freely available software system for 3D computer graphics
