    # This file created by conda-build 2.0.7
    # meta.yaml template originally from:
    # /Users/sansomk/code/python/condarecipes/meshio, last modified Mon Oct 24 23:38:15 2016
    # ------------------------------------------------

    package:
        name: pipdate
        version: 0.3.2
    source:
        git_url: https://github.com/nschloe/pipdate.git
        git_tag: v0.3.2
    build:
        number: '0'
    requirements:
        build:
            - python
            - appdirs
            - requests
        run:
            - appdirs
            - requests
    #test:
    #    imports:
    #        - pipdate # this fails for some reason?

    about:
        home: https://github.com/nschloe/pipdate.git
        license: MIT License
        summary: check for updates on PyPi
